apiVersion: apps/v1
kind: Deployment
metadata:
  name: display-noaddress
spec:
  selector:
    matchLabels:
      app: display
  replicas: 1
  template: 
    metadata:
      labels:
        app: display
        version: noaddress
    spec:
      containers:
      - name: display
        image: kunchalavikram/istio-ms-display-noaddress:1.0
        env:
        - name: dualstack
          value: ipv4
        - name: delay_in_request_processing
          value: "0"
        - name: deploy
          value: k8s 
        - name: propogate_headers
          value: "true"
        - name: background_color
          value: "green"
        - name: text_color
          value: "white"       
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: display
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 5000
    nodePort: 30100
  selector:
    app: display
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hobby
spec:
  selector:
    matchLabels:
      app: hobby
  replicas: 1
  template: 
    metadata:
      labels:
        app: hobby
    spec:
      containers:
      - name: hobby
        image: kunchalavikram/istio-ms-hobby:1.0
        env:
        - name: dualstack
          value: ipv4
        - name: delay_in_request_processing
          value: "0"
        - name: deploy
          value: k8s 
        - name: propogate_headers
          value: "true"
        - name: random_fail
          value: "false"   
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: hobby
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 5001
  selector:
    app: hobby
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo-v1
spec:
  selector:
    matchLabels:
      app: photo
  replicas: 9
  template: 
    metadata:
      labels:
        app: photo
        version: v1
    spec:
      containers:
      - name: photo
        image: kunchalavikram/istio-ms-nophoto:1.0
        env:
        - name: dualstack
          value: ipv4
        - name: delay_in_request_processing
          value: "0"
        - name: deploy
          value: k8s 
        - name: propogate_headers
          value: "true"  
        imagePullPolicy: IfNotPresent
---        
apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo-v2
spec:
  selector:
    matchLabels:
      app: photo
  replicas: 1
  template: 
    metadata:
      labels:
        app: photo
        version: v2
    spec:
      containers:
      - name: photo
        image: kunchalavikram/istio-ms-photo:1.0
        env:
        - name: dualstack
          value: ipv4
        - name: delay_in_request_processing
          value: "0"
        - name: deploy
          value: k8s 
        - name: propogate_headers
          value: "true"
        - name: random_fail
          value: "false" 
        - name: fail_count
          value: "5"   
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: photo
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 5002
  selector:
    app: photo